### PR TITLE
Closes #125

### LINKED ISSUE #125: CLI is broken
When using the CLI the classpath is not working, which results in the CLI indicating an error:

Could not find or load main class com.eharmony.aloha.cli.Cli

Steps Repo
1. git clone https://github.com/eHarmony/aloha.git
2. cd aloha.
3. sbt compile
4. aloha-cli/bin/aloha-cli \
-cp $(find $PWD/aloha-cli -name "*.jar" | grep dep):\
$(find $PWD/aloha-core -name "*.jar" | grep test) \
--dataset \
-s $(find $PWD/aloha-core/src -name 'proto_spec2.json')\
-p com.eharmony.aloha.test.proto.Testing.UserProto \
-i $(find $PWD/aloha-core/src -name 'fizz_buzzs.proto')\
--vw_labeled /tmp/dataset.vw

Discussions with Jon Morra, this is a result of migrating from Maven to SBT.   Ideal fix, in the SBT add in a references to the missing Jars.

### PR DESCRIPTION
**Pull request by deaktator**

### CODE REVIEW

**Comment by deaktator** [comment]
@danny-lupinelli-zefr, please take a look and tell me what you think.  I updated the `aloha-cli` shell script and it works but it's slow because of the line:

```bash
CP=$(sbt "export runtime:fullClasspath" | tail -n1)
```

Do you think that we should allow the specification of a classpath file or something?

**Comment by deaktator** [comment]
To try it out: 

```bash
# cd and compile code
cd aloha
sbt compile test:compile

# Create a cache directory (optional).  If you don't create one, 
# don't supply --cachedir below.
mkdir -p /tmp/aloha-cache-dir

(echo "CAESBEFsYW4YASUAALhBKg0IARABGQAAAAAAAPA/Kg0IAhACGQAAAAAAAABA"
 echo "CAESBEthdGUYAioNCAMQAxkAAAAAAAAIQA==") \
 |\
$PWD/aloha-cli/bin/aloha-cli \
  -cp "$PWD/aloha-io-proto/target/scala-2.11/test-classes:$PWD/aloha-core/target/scala-2.11/test-classes" \
  --dataset \
  --cachedir /tmp/aloha-cache-dir \
  -s $(find $PWD -name 'proto_spec1.js' | head -n1)       \
  -p com.eharmony.aloha.test.proto.Testing.UserProto \
  --vw -

rm -rf /tmp/aloha-cache-dir
```

**Comment by deaktator** [comment]
## Using the Script

The CLI script can be used from any directory but the following shows how to use it from within the Aloha root directory.  To use, the classes need to be compiled.  If a *class cache directory* is specified, it must exist.  

The script will attempt to find the `aloha-cli/.classpath` file.  If it doesn't exist, the CLI script will produce it using SBT, which takes a fair amount of time (10 seconds).  Start up time in subsequent runs will be vastly improved if the `aloha-cli/.classpath` exists.  While a *class cache directory* is not required, it will also dramatically speed up additional runs.

### Compiling

```bash
cd aloha # change to the Aloha root directory.
sbt compile test:compile # test:compile for protos in test directory
```

### Creating a class cache directory (if desired)

```bash
rm -rf /tmp/aloha-cache-dir  # delete old cache dir if desired
rm -f aloha-cli/.classpath # delete old .classpath file if desired.
mkdir -p /tmp/aloha-cache-dir  # Make cache dir not there.
```

### Example protocol buffer example.
```bash
## This is in zsh

time \
  echo -e "CAESBEFsYW4YASUAALhBKg0IARABGQAAAAAAAPA/Kg0IAhACGQAAAAAAAABA\nCAESBEthdGUYAioNCAMQAxkAAAAAAAAIQA==" \
  |                                                         \
  $PWD/aloha-cli/bin/aloha-cli                              \
    -cp "$PWD/aloha-io-proto/target/scala-2.11/test-classes:\
$PWD/aloha-core/target/scala-2.11/test-classes"             \
    --dataset                                               \
    --cachedir /tmp/aloha-cache-dir                         \
    -s $(find $PWD -name 'proto_spec1.js' | head -n1)       \
    -p com.eharmony.aloha.test.proto.Testing.UserProto      \
    --vw -
```

*Notice the time is **17.896** seconds!*

```
| name=Alan gender=MALE bmi:23 num_photos:2
| name=Kate gender=FEMALE bmi=UNK num_photos
echo -e   0.00s user 0.00s system 1% cpu 0.047 total
$PWD/aloha-cli/bin/aloha-cli -cp  --dataset --cachedir /tmp/aloha-cache-dir -  46.43s user 2.34s system 272% cpu 17.896 total
```

```bash
!! # [Enter] [Enter]
```

*On this run, the time is **2.497** seconds!*

```
| name=Alan gender=MALE bmi:23 num_photos:2
| name=Kate gender=FEMALE bmi=UNK num_photos
echo -e   0.00s user 0.00s system 1% cpu 0.051 total
$PWD/aloha-cli/bin/aloha-cli -cp  --dataset --cachedir /tmp/aloha-cache-dir -  6.02s user 0.48s system 260% cpu 2.497 total
```

**Review by vsuthichai — APPROVED** [review]
Approved!

**Pull request merged**
