### PR TITLE
closes #87

### LINKED ISSUE #87: add JSON function to aloha-h2o
add a JSON function like on line 282 of https://github.com/eHarmony/aloha/blob/master/aloha-vw-jni/src/main/scala/com/eharmony/aloha/models/vw/jni/VwJniModel.scala

This will make it easier to _create_ H<sub>2</sub>O models

### PR DESCRIPTION
**Pull request by deaktator**
This change is [Reviewable](https://reviewable.io/reviews/eharmony/aloha/89)

### CODE REVIEW

**Comment by jmorra** [comment]
Why is this appropriate?  It doesn't follow the convention in `VWJniModel`.

<details><summary>

<i>Previously, deaktator (Ryan Deak) wrote…</i></summary>



> #### closes #87
> 
> </details>

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[aloha-h2o/src/main/scala/com/eharmony/aloha/models/h2o/H2oModel.scala, line 252 [r1]](https://reviewable.io:443/reviews/eharmony/aloha/89#-KHMq3uQvy3yYWXOkwsb:-KHMq3uQvy3yYWXOkwsc:-1234244528) ([raw file](https://github.com/eharmony/aloha/blob/0d3354d853c2806a65a36d7e8c5a099ac43dddd3/aloha-h2o/src/main/scala/com/eharmony/aloha/models/h2o/H2oModel.scala#L252)):_

> ``` Scala
>     }
>   }
> ```

I know that we went through an issue with `VWJniModel` where the VFS type was messing us up.  Is that addressed here?

---

_[aloha-h2o/src/main/scala/com/eharmony/aloha/models/h2o/H2oModel.scala, line 258 [r1]](https://reviewable.io:443/reviews/eharmony/aloha/89#-KHMqEmwuh04OX2VSZjA:-KHMqEmwuh04OX2VSZjB:-322464991) ([raw file](https://github.com/eharmony/aloha/blob/0d3354d853c2806a65a36d7e8c5a099ac43dddd3/aloha-h2o/src/main/scala/com/eharmony/aloha/models/h2o/H2oModel.scala#L258)):_

> ``` Scala
>                              externalModel: Boolean = false,
>                              numMissingThreshold: Option[Int] = None,
>                              notes: Option[Seq[String]] = None): Either[String, JsValue] = {
> ```

Why is this return type different from `VWJniModel.json`?  I would think they should be the same.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/eharmony/aloha/89#-:-KHMpaOpcy-kc9xFthEu:498098493)_

**Comment by deaktator** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[aloha-h2o/src/main/scala/com/eharmony/aloha/models/h2o/H2oModel.scala, line 252 [r1]](https://reviewable.io:443/reviews/eharmony/aloha/89#-KHMq3uQvy3yYWXOkwsb:-KHMwMc8rwO316a-26s5:-1403641361) ([raw file](https://github.com/eharmony/aloha/blob/0d3354d853c2806a65a36d7e8c5a099ac43dddd3/aloha-h2o/src/main/scala/com/eharmony/aloha/models/h2o/H2oModel.scala#L252)):_
<details><summary>

<i>Previously, jmorra (Jon Morra) wrote…</i></summary>



> I know that we went through an issue with `VWJniModel` where the VFS type was messing us up.  Is that addressed here?</details>
> This uses the same structure as the VW JNI model `json`  function so if it was resolved, the same should work here.

---

_[aloha-h2o/src/main/scala/com/eharmony/aloha/models/h2o/H2oModel.scala, line 258 [r1]](https://reviewable.io:443/reviews/eharmony/aloha/89#-KHMqEmwuh04OX2VSZjA:-KHMwl0ZDHwwc3RGB7t1:-1157800644) ([raw file](https://github.com/eharmony/aloha/blob/0d3354d853c2806a65a36d7e8c5a099ac43dddd3/aloha-h2o/src/main/scala/com/eharmony/aloha/models/h2o/H2oModel.scala#L258)):_
<details><summary>

<i>Previously, jmorra (Jon Morra) wrote…</i></summary>



> Why is this return type different from `VWJniModel.json`?  I would think they should be the same.</details>
> Will make it consistent with the other like functions.  It will throw instead of return an error.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/eharmony/aloha/89)_

**Comment by deaktator** [comment]
Reviewed 2 of 3 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/eharmony/aloha/89)_

**Comment by deaktator** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[aloha-h2o/src/main/scala/com/eharmony/aloha/models/h2o/H2oModel.scala, line 252 [r1]](https://reviewable.io:443/reviews/eharmony/aloha/89#-KHMq3uQvy3yYWXOkwsb:-KHN3Xlh6mC8Snjjcbou:-499146009) ([raw file](https://github.com/eharmony/aloha/blob/0d3354d853c2806a65a36d7e8c5a099ac43dddd3/aloha-h2o/src/main/scala/com/eharmony/aloha/models/h2o/H2oModel.scala#L252)):_
<details><summary>

<i>Previously, deaktator (Ryan Deak) wrote…</i></summary>



> This uses the same structure as the VW JNI model `json`  function so if it was resolved, the same should work here.</details>
> Done.

---

_[aloha-h2o/src/main/scala/com/eharmony/aloha/models/h2o/H2oModel.scala, line 258 [r1]](https://reviewable.io:443/reviews/eharmony/aloha/89#-KHMqEmwuh04OX2VSZjA:-KHN3X60ZegYN92W-Tte:-499146009) ([raw file](https://github.com/eharmony/aloha/blob/0d3354d853c2806a65a36d7e8c5a099ac43dddd3/aloha-h2o/src/main/scala/com/eharmony/aloha/models/h2o/H2oModel.scala#L258)):_
<details><summary>

<i>Previously, deaktator (Ryan Deak) wrote…</i></summary>



> Will make it consistent with the other like functions.  It will throw instead of return an error.</details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/eharmony/aloha/89)_

**Pull request merged**
