### PR TITLE
24 bug fix bag of words

### PR DESCRIPTION
**Pull request by deaktator**
Fixed the k-skip n-gram algorithm and added tests.  Updates:
1. Renamed the files and objects to SkipGrams.
2. Updated `BasicFunctions` to pull in SkipGrams functions
3. Created a parallel version of SkipGrams in the SkipGrams object.
4. Updated docs a little
5. Created a reusable fast, thread-safe, memory-efficient k-subsequence iterator in aloha-core ../aloha/util/`SubSeqIterator`
6. Added `MapImplicitRegressionConversion` to convert maps to maps that adhere to the interface in the regression models.  Added it to `BasicFunctions`

Place take a look.

### CODE REVIEW

**Comment by jmorra** [comment]
The tests look reasonable, but the code looks awfully complex for BoW.  Are there other generalizations that this code is capable of?

**Comment by deaktator** [comment]
Which part is to complex?

**Comment by deaktator** [comment]
Oh, I think I know what you're saying. Specialized, dumbed down algo for BoW, to avoid the complexity of k-skip n-grams.

**Comment by deaktator** [comment]
I just thought about the myriad of performance problems. I'm going to squash the PR, refactor and start again. I am going to opt for performance over simplicity so I'll make optimizations of the stupid things I found when I looked at it again.

**Pull request merged**
