### PR TITLE
Closes #104

### LINKED ISSUE #104: Create a Manifest String parser
Create a parser that reads `String`s and produces `scala.reflect.Manifest`.  Something like: 

``` scala
import scala.util.parsing.combinator.JavaTokenParsers
import scala.reflect.{Manifest, ManifestFactory}

/**
 * Parser that takes string input and constructs `scala.reflect.Manifest` instances.
 * {{{
 * // Example usages:
 *
 * // Either[String,scala.reflect.Manifest[_]]
 * val em = ManifestParser.parse("scala.collection.immutable.List[scala.Double]")
 * assert("scala.collection.immutable.List[Double]" == em.right.get.toString)
 *
 * val em2 = ManifestParser.parse("scala.collection.immutable.Map[Int, scala.Float]")
 * assert("scala.collection.immutable.Map[Int, Float]" == em2.right.get.toString)
 * }}}
 * @author deaktator
 */
object ManifestParser extends JavaTokenParsers {
  def parse(strRep: CharSequence): Either[String, Manifest[_]] = {
    try {
      parseAll(manifest, strRep) match {
        case Success(man, _)    => Right(man)
        case Error(err, next)   => Left(errorMsg(strRep, err, next))
        case Failure(err, next) => Left(errorMsg(strRep, err, next))
      }
    }
    catch {
      case ex: ClassNotFoundException => 
        Left(s"For $strRep, class not found: ${ex.getMessage}")
    }
  }

  private[this] def errorMsg(strRep: CharSequence, err: String, next: Input): String = {
    val whiteSpace = Seq.fill(next.offset + 1)(" ").mkString("")
    s"Problem at character ${next.offset}:\n'$strRep\n$whiteSpace^\n$err"
  }

  private[this] lazy val path = rep1sep(ident, ".") ^^ { ids => ids.mkString(".") }

  // Should suppress erasure warnings
  private[this] lazy val manifest: Parser[Manifest[_]] = 
    ((path ~ ("[" ~> (rep1sep(manifest, ",") <~ "]"))) | path) ^^ {
      case (tpe: String) ~ (typeParams: Seq[Manifest[_]]) => parametrizedManifest(tpe, typeParams)
      case tpe: String                                    => unparametrizedManifest(tpe)
    }

  private[this] def parametrizedManifest(tpe: String, typeParams: Seq[Manifest[_]]): Manifest[_] = {
    val clas = Class.forName(tpe)
    val (Seq(first), rest) = typeParams.splitAt(1)
    ManifestFactory.classType(clas, first, rest:_*)
  }

  private[this] def unparametrizedManifest(tpe: String): Manifest[_] = {
    tpe.replaceFirst("""^scala\.""", "") match {
      case "Any"     => ManifestFactory.Any
      case "AnyVal"  => ManifestFactory.AnyVal
      case "AnyRef"  => ManifestFactory.AnyRef
      case "Boolean" => ManifestFactory.Boolean
      case "Byte"    => ManifestFactory.Byte
      case "Char"    => ManifestFactory.Char
      case "Double"  => ManifestFactory.Double
      case "Float"   => ManifestFactory.Float
      case "Int"     => ManifestFactory.Int
      case "Long"    => ManifestFactory.Long
      case "Short"   => ManifestFactory.Short

      // Special values.
      case "Nothing" => ManifestFactory.Nothing
      case "Unit"    => ManifestFactory.Unit

      // Default: construct a class Manifest.
      case _         => ManifestFactory.classType(Class.forName(tpe))
    }
  }
}
```

### PR DESCRIPTION
**Pull request by deaktator**
See #104 for documentation..

---

This change is [Reviewable](https://reviewable.io/reviews/eharmony/aloha/106)

### CODE REVIEW

**Comment by deaktator** [comment]
Reviewed 1 of 2 files at r1, 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

_[aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala, line 34 [r1]](https://reviewable.io:443/reviews/eharmony/aloha/106#-KPPYDam1pXycM9FPv66:-KPPYDam1pXycM9FPv67:bm6wi2n) ([raw file](https://github.com/eharmony/aloha/blob/29d4cfa4483d519a9c3670007ce30123a95cbd04/aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala#L34)):_

> ``` Scala
>     * @return either an error on the left or a `Manifest` (missing it's type parameter)
>     *         on the right
>     */
> ```

This is the only public API exposed.

---

_[aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala, line 67 [r1]](https://reviewable.io:443/reviews/eharmony/aloha/106#-KPPYTTkI2CXhtYetM0q:-KPPYTTkI2CXhtYetM0r:b-t7xson) ([raw file](https://github.com/eharmony/aloha/blob/29d4cfa4483d519a9c3670007ce30123a95cbd04/aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala#L67)):_

> ``` Scala
>     * @author deaktator
>     */
>   private[this] object Grammar extends RegexParsers {
> ```

The entire grammar for the parser is defined in `Grammar` and it is private so it can only be used by `ManifestParser`.

---

_[aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala, line 74 [r1]](https://reviewable.io:443/reviews/eharmony/aloha/106#-KPPYiJm0C7L_DbzBoKS:-KPPYiJm0C7L_DbzBoKT:b-p0brk) ([raw file](https://github.com/eharmony/aloha/blob/29d4cfa4483d519a9c3670007ce30123a95cbd04/aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala#L74)):_

> ``` Scala
>      - ''it is the root production''
>      - `withArg` ''and'' `array` ''rules refer to this rule, making it recursively thereby necessitating the type.''
>       */
> ```

**ROOT PRODUCTION RULE:**

---

_[aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala, line 92 [r1]](https://reviewable.io:443/reviews/eharmony/aloha/106#-KPPZ5dJQr2iQITsvPZ4:-KPPZ5dKk-9Az4Bi84be:b-lylx39) ([raw file](https://github.com/eharmony/aloha/blob/29d4cfa4483d519a9c3670007ce30123a95cbd04/aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala#L92)):_

> ``` Scala
>     }
> 
>     lazy val noArg = special | classManifest
> ```

Notice `special` occurs first.  This is important.

---

_[aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala, line 115 [r1]](https://reviewable.io:443/reviews/eharmony/aloha/106#-KPPZCTi1xnOM_DryRIo:-KPPZCTi1xnOM_DryRIp:b1xavg6) ([raw file](https://github.com/eharmony/aloha/blob/29d4cfa4483d519a9c3670007ce30123a95cbd04/aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala#L115)):_

> ``` Scala
>     lazy val short   = "Short"   ^^^ ManifestFactory.Short
>     lazy val unit    = "Unit"    ^^^ ManifestFactory.Unit
> ```

All production rules below are basic string tokens.  `path` is the most important as this is used in the `classManifest` and `withArg` productions and represents a canonical class name.

---

_[aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala, line 129 [r1]](https://reviewable.io:443/reviews/eharmony/aloha/106#-KPP_bIHygJ-bUR5g2PB:-KPP_bIHygJ-bUR5g2PC:b-6nzv6v) ([raw file](https://github.com/eharmony/aloha/blob/29d4cfa4483d519a9c3670007ce30123a95cbd04/aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala#L129)):_

> ``` Scala
> 
>   // vvvvvvvvvv   Functions for transforming input to Manifest instances.   vvvvvvvvvv
>   // TODO: These should be package private for testing.
> ```

Remove this.

---

_[aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala, line 130 [r1]](https://reviewable.io:443/reviews/eharmony/aloha/106#-KPP_hMOG5nwOIvvjbJq:-KPP_hMOG5nwOIvvjbJr:b-on3oqh) ([raw file](https://github.com/eharmony/aloha/blob/29d4cfa4483d519a9c3670007ce30123a95cbd04/aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala#L130)):_

> ``` Scala
>   // vvvvvvvvvv   Functions for transforming input to Manifest instances.   vvvvvvvvvv
>   // TODO: These should be package private for testing.
> ```

Add scaladoc and tests for this.

---

_[aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala, line 141 [r1]](https://reviewable.io:443/reviews/eharmony/aloha/106#-KPPZvT8BEwGvEcAGYbS:-KPPZvT8BEwGvEcAGYbT:b-cmxlcs) ([raw file](https://github.com/eharmony/aloha/blob/29d4cfa4483d519a9c3670007ce30123a95cbd04/aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala#L141)):_

> ``` Scala
>     ManifestFactory.classType(clas, first.head, rest:_*)
>   }
> }
> ```

Ut oh.  Add a line break.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/eharmony/aloha/106)_

**Comment by deaktator** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/eharmony/aloha/106)_

**Comment by deaktator** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala, line 22 [r1]](https://reviewable.io:443/reviews/eharmony/aloha/106#-KPPfsClraflhk1Cwmue:-KPPfsClraflhk1Cwmuf:bcnfgpo) ([raw file](https://github.com/eharmony/aloha/blob/29d4cfa4483d519a9c3670007ce30123a95cbd04/aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala#L22)):_

> ``` Scala
>   * @author deaktator
>   */
> object ManifestParser {
> ```

Should this class be package private?  I think so.

---

_[aloha-core/src/main/scala/com/eharmony/aloha/reflect/RefInfo.scala, line 38 [r3]](https://reviewable.io:443/reviews/eharmony/aloha/106#-KPPg-i_eQgwWGJMVZIs:-KPPg-i_eQgwWGJMVZIt:bdjzfr8) ([raw file](https://github.com/eharmony/aloha/blob/637b778ec7f681e6d082b68b731ee665cb2b2230/aloha-core/src/main/scala/com/eharmony/aloha/reflect/RefInfo.scala#L38)):_

> ``` Scala
>     *         the Right for a success.
>     */
>     def fromString(strRep: String): Either[String, RefInfo[_]] =
> ```

This should be the de facto way to retrieve a `RefInfo` from a String.  The ManifestParser should not be used directly as that would break the `RefInfo` abstraction.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/eharmony/aloha/106)_

**Comment by sahil-goyal** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala, line 22 [r1]](https://reviewable.io:443/reviews/eharmony/aloha/106#-KPPfsClraflhk1Cwmue:-KPPw7mFCTZ4YAD334O4:btd51a6) ([raw file](https://github.com/eharmony/aloha/blob/29d4cfa4483d519a9c3670007ce30123a95cbd04/aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala#L22)):_
<details><summary>

<i>Previously, deaktator (Ryan Deak) wrote…</i></summary>



> Should this class be package private?  I think so.
> </details>
> I agree.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/eharmony/aloha/106)_

**Comment by jmorra** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala, line 22 [r1]](https://reviewable.io:443/reviews/eharmony/aloha/106#-KPPfsClraflhk1Cwmue:-KPTwNYuhD-FWPbLhpbB:b-4euayv) ([raw file](https://github.com/eharmony/aloha/blob/29d4cfa4483d519a9c3670007ce30123a95cbd04/aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala#L22)):_
<details><summary>

<i>Previously, sahil-goyal wrote…</i></summary>



> I agree.
> </details>
> I don't think so, this could be super useful elsewhere.  So useful it could warrant its own project.  

---

_[aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala, line 92 [r1]](https://reviewable.io:443/reviews/eharmony/aloha/106#-KPPZ5dJQr2iQITsvPZ4:-KPTwbhuuCWdHr2B5ScK:bb76mu4) ([raw file](https://github.com/eharmony/aloha/blob/29d4cfa4483d519a9c3670007ce30123a95cbd04/aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala#L92)):_
<details><summary>

<i>Previously, deaktator (Ryan Deak) wrote…</i></summary>



> Notice `special` occurs first.  This is important.
> </details>
> Why?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/eharmony/aloha/106)_

**Comment by jmorra** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/eharmony/aloha/106)_

**Comment by deaktator** [comment]
Reviewed 3 of 4 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala, line 22 [r1]](https://reviewable.io:443/reviews/eharmony/aloha/106#-KPPfsClraflhk1Cwmue:-KPVMbkA7rsL6WuDDtNb:br45kha) ([raw file](https://github.com/eharmony/aloha/blob/29d4cfa4483d519a9c3670007ce30123a95cbd04/aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala#L22)):_
<details><summary>

<i>Previously, jmorra (Jon Morra) wrote…</i></summary>



> I don't think so, this could be super useful elsewhere.  So useful it could warrant its own project.  
> </details>
> Agree.  https://github.com/deaktator/scala-runtime-manifest

``` xml
<dependency>
  <groupId>com.github.deaktator</groupId>
  <artifactId>scala-runtime-manifest_2.10</artifactId>
  <version>0.0.1</version>
</dependency>
```

---

_[aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala, line 92 [r1]](https://reviewable.io:443/reviews/eharmony/aloha/106#-KPPZ5dJQr2iQITsvPZ4:-KPVMZRz2hZQg2o9n6VH:b-896fix) ([raw file](https://github.com/eharmony/aloha/blob/29d4cfa4483d519a9c3670007ce30123a95cbd04/aloha-core/src/main/scala/com/eharmony/aloha/reflect/ManifestParser.scala#L92)):_
<details><summary>

<i>Previously, jmorra (Jon Morra) wrote…</i></summary>



> Why?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/eharmony/aloha/106)_

**Pull request merged**
