### PR TITLE
Closes #117

### LINKED ISSUE #117: Create SBT-based build with cross compilation
Create an SBT-based build with cross compilation.  This should at least support 2.10 and 2.11 but should hopefully include 2.12 as well.  

This needs to be a multi-module build for all of the sub-modules.

### PR DESCRIPTION
**Pull request by deaktator**
Create an SBT-based cross build of Aloha for 2.10 and 2.11.

### CODE REVIEW

**Comment by deaktator** [comment]
Still need to eliminate a lot of compiler warnings.  Start with used imports, unused local vars and dead code.

**Comment by deaktator** [comment]
Updated code to remove compiler warnings and fixed the bugs indicated by those warnings.  Now there are only a few warnings not related to compiler bugs.

**Comment by deaktator** [comment]
@sahil-goyal Can you please review.  I think this can now be merged.

**Comment by deaktator** [comment]
Actually, need to remove the maven POM files before merging.

**Comment by deaktator** [comment]
## *aloha-core* differences:
`scala-runtime-manifest_2.10:0.0.1` → `scala-runtime-manifest_2.10:1.0.0`
`scalaz-core_2.10:7.0.0` → `scalaz-core_2.10:7.0.6`

## *aloha-vw-jni* differences:
`scala-runtime-manifest_2.10:0.0.1` → `scala-runtime-manifest_2.10:1.0.0`
`scalaz-core_2.10:7.0.0` → `scalaz-core_2.10:7.0.6`

## *aloha-h2o* differences:
`scala-runtime-manifest_2.10:0.0.1` → `scala-runtime-manifest_2.10:1.0.0`
`scalaz-core_2.10:7.0.0` → `scalaz-core_2.10:7.0.6`

## *aloha-cli* differences:
`scala-runtime-manifest_2.10:0.0.1` → `scala-runtime-manifest_2.10:1.0.0`
`scalaz-core_2.10:7.0.0` → `scalaz-core_2.10:7.0.6`
`guava:16.0.1` → `guava:16.0.1


## Old *aloha-core* Maven Dependencies

```
com.eharmony:aloha-proto:2.0.1
com.fasterxml:classmate:1.0.0
com.github.deaktator:scala-runtime-manifest_2.10:0.0.1
com.github.multiworldtesting:explore-java:1.0.0
com.github.scopt:scopt_2.10:3.3.0
com.google.code.findbugs:annotations:2.0.1
com.google.guava:guava:15.0
com.google.protobuf:protobuf-java:2.4.1
com.twitter:util-core_2.10:6.27.0
com.twitter:util-function_2.10:6.27.0
commons-codec:commons-codec:1.10
commons-io:commons-io:2.4
commons-logging:commons-logging:1.1.1
commons-vfs:commons-vfs:1.0
io.spray:spray-json_2.10:1.3.1
org.apache.commons:commons-vfs2:2.0
org.javassist:javassist:3.18.2-GA
org.reflections:reflections:0.9.9
org.scala-lang:scala-compiler:2.10.5
org.scala-lang:scala-library:2.10.5
org.scala-lang:scala-reflect:2.10.5
org.scalaz:scalaz-core_2.10:7.0.0
org.slf4j:slf4j-api:1.7.10
```

## New *aloha-core* SBT Dependencies

```
com.eharmony:aloha-proto:2.0.1
com.fasterxml:classmate:1.0.0
com.github.deaktator:scala-runtime-manifest_2.10:1.0.0
com.github.multiworldtesting:explore-java:1.0.0
com.github.scopt:scopt_2.10:3.3.0
com.google.code.findbugs:annotations:2.0.1
com.google.guava:guava:15.0
com.google.protobuf:protobuf-java:2.4.1
com.twitter:util-core_2.10:6.27.0
com.twitter:util-function_2.10:6.27.0
commons-codec:commons-codec:1.10
commons-io:commons-io:2.4
commons-logging:commons-logging:1.1.1
commons-vfs:commons-vfs:1.0
io.spray:spray-json_2.10:1.3.1
org.apache.commons:commons-vfs2:2.0
org.javassist:javassist:3.18.2-GA
org.reflections:reflections:0.9.9
org.scala-lang:scala-compiler:2.10.5
org.scala-lang:scala-reflect:2.10.5
org.scalaz:scalaz-core_2.10:7.0.6
org.slf4j:slf4j-api:1.7.10
```


## Old *aloha-vw-jni* Maven Dependencies

```
com.eharmony:aloha-core:3.3.2-SNAPSHOT
com.eharmony:aloha-proto:2.0.1
com.fasterxml:classmate:1.0.0
com.github.deaktator:scala-runtime-manifest_2.10:0.0.1
com.github.johnlangford:vw-jni:8.1.0
com.github.multiworldtesting:explore-java:1.0.0
com.github.scopt:scopt_2.10:3.3.0
com.google.code.findbugs:annotations:2.0.1
com.google.guava:guava:15.0
com.google.protobuf:protobuf-java:2.4.1
com.twitter:util-core_2.10:6.27.0
com.twitter:util-function_2.10:6.27.0
commons-codec:commons-codec:1.10
commons-io:commons-io:2.4
commons-logging:commons-logging:1.1.1
commons-vfs:commons-vfs:1.0
io.spray:spray-json_2.10:1.3.1
org.apache.commons:commons-vfs2:2.0
org.javassist:javassist:3.18.2-GA
org.reflections:reflections:0.9.9
org.scala-lang:scala-compiler:2.10.5
org.scala-lang:scala-library:2.10.5
org.scala-lang:scala-reflect:2.10.5
org.scalaz:scalaz-core_2.10:7.0.0
org.slf4j:slf4j-api:1.7.10
```

## New *aloha-vw-jni* SBT Dependencies

```
com.eharmony:aloha-core_2.10:3.3.2-SNAPSHOT
com.eharmony:aloha-proto:2.0.1
com.eharmony:aloha-vw-jni_2.10:3.3.2-SNAPSHOT
com.fasterxml:classmate:1.0.0
com.github.deaktator:scala-runtime-manifest_2.10:1.0.0
com.github.johnlangford:vw-jni:8.1.0
com.github.multiworldtesting:explore-java:1.0.0
com.github.scopt:scopt_2.10:3.3.0
com.google.code.findbugs:annotations:2.0.1
com.google.guava:guava:15.0
com.google.protobuf:protobuf-java:2.4.1
com.twitter:util-core_2.10:6.27.0
com.twitter:util-function_2.10:6.27.0
commons-codec:commons-codec:1.10
commons-io:commons-io:2.4
commons-logging:commons-logging:1.1.1
commons-vfs:commons-vfs:1.0
io.spray:spray-json_2.10:1.3.1
org.apache.commons:commons-vfs2:2.0
org.javassist:javassist:3.18.2-GA
org.reflections:reflections:0.9.9
org.scala-lang:scala-compiler:2.10.5
org.scala-lang:scala-reflect:2.10.5
org.scalaz:scalaz-core_2.10:7.0.6
org.slf4j:slf4j-api:1.7.10
```

## Old *aloha-h2o* Maven Dependencies

```
ai.h2o:google-analytics-java:1.1.2-H2O-CUSTOM:runtime
ai.h2o:h2o-core:3.8.2.3:compile
ai.h2o:h2o-genmodel:3.8.2.3:compile
com.eharmony:aloha-proto:2.0.1:compile
com.fasterxml:classmate:1.0.0:compile
com.github.deaktator:scala-runtime-manifest_2.10:0.0.1:compile
com.github.multiworldtesting:explore-java:1.0.0:compile
com.github.rwl:jtransforms:2.4.0:runtime
com.github.scopt:scopt_2.10:3.3.0:compile
com.github.tony19:named-regexp:0.2.3:runtime
com.google.code.findbugs:annotations:2.0.1:compile
com.google.code.gson:gson:2.3.1:runtime
com.google.guava:guava:16.0.1:compile
com.google.protobuf:protobuf-java:2.4.1:compile
com.twitter:util-core_2.10:6.27.0:compile
com.twitter:util-function_2.10:6.27.0:compile
commons-codec:commons-codec:1.10:compile
commons-collections:commons-collections:3.0:runtime
commons-httpclient:commons-httpclient:3.1:runtime
commons-io:commons-io:2.4:compile
commons-lang:commons-lang:2.6:runtime
commons-logging:commons-logging:1.1.1:compile
commons-vfs:commons-vfs:1.0:compile
gov.nist.math:jama:1.0.3:runtime
io.spray:spray-json_2.10:1.3.1:compile
joda-time:joda-time:2.3:runtime
net.java.dev.jets3t:jets3t:0.6.1:runtime
org.apache.commons:commons-math3:3.3:runtime
org.apache.commons:commons-vfs2:2.0:compile
org.apache.directory.studio:org.apache.commons.lang:2.6:runtime
org.apache.httpcomponents:httpclient:4.1:runtime
org.apache.httpcomponents:httpcore:4.1:runtime
org.eclipse.jetty:jetty-continuation:8.1.17.v20150415:runtime
org.eclipse.jetty:jetty-http:8.1.17.v20150415:runtime
org.eclipse.jetty:jetty-io:8.1.17.v20150415:runtime
org.eclipse.jetty:jetty-jndi:8.1.17.v20150415:runtime
org.eclipse.jetty:jetty-plus:8.1.17.v20150415:runtime
org.eclipse.jetty:jetty-security:8.1.17.v20150415:runtime
org.eclipse.jetty:jetty-server:8.1.17.v20150415:runtime
org.eclipse.jetty:jetty-servlet:8.1.17.v20150415:runtime
org.eclipse.jetty:jetty-util:8.1.17.v20150415:runtime
org.eclipse.jetty:jetty-webapp:8.1.17.v20150415:runtime
org.eclipse.jetty:jetty-xml:8.1.17.v20150415:runtime
org.eclipse.jetty.aggregate:jetty-servlet:8.1.17.v20150415:runtime
org.eclipse.jetty.orbit:javax.activation:1.1.0.v201105071233:runtime
org.eclipse.jetty.orbit:javax.mail.glassfish:1.4.1.v201005082020:runtime
org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016:runtime
org.eclipse.jetty.orbit:javax.transaction:1.1.1.v201105210645:runtime
org.javassist:javassist:3.18.2-GA:compile
org.reflections:reflections:0.9.9:compile
org.scala-lang:scala-compiler:2.10.5:compile
org.scala-lang:scala-library:2.10.5:compile
org.scala-lang:scala-reflect:2.10.5:compile
org.scalaz:scalaz-core_2.10:7.0.0:compile
org.slf4j:slf4j-api:1.7.10:compile
```

## New *aloha-h2o* SBT Dependencies

```
ai.h2o:google-analytics-java:1.1.2-H2O-CUSTOM
ai.h2o:h2o-core:3.8.2.3
ai.h2o:h2o-genmodel:3.8.2.3
com.eharmony:aloha-proto:2.0.1
com.fasterxml:classmate:1.0.0
com.github.deaktator:scala-runtime-manifest_2.10:1.0.0
com.github.multiworldtesting:explore-java:1.0.0
com.github.rwl:jtransforms:2.4.0
com.github.scopt:scopt_2.10:3.3.0
com.github.tony19:named-regexp:0.2.3
com.google.code.findbugs:annotations:2.0.1
com.google.code.gson:gson:2.3.1
com.google.guava:guava:16.0.1
com.google.protobuf:protobuf-java:2.4.1
com.twitter:util-core_2.10:6.27.0
com.twitter:util-function_2.10:6.27.0
commons-codec:commons-codec:1.10
commons-collections:commons-collections:3.0
commons-httpclient:commons-httpclient:3.1
commons-io:commons-io:2.4
commons-lang:commons-lang:2.6
commons-logging:commons-logging:1.1.1
commons-vfs:commons-vfs:1.0
gov.nist.math:jama:1.0.3
io.spray:spray-json_2.10:1.3.1
joda-time:joda-time:2.3
net.java.dev.jets3t:jets3t:0.6.1
org.apache.commons:commons-math3:3.3
org.apache.commons:commons-vfs2:2.0
org.apache.directory.studio:org.apache.commons.lang:2.6
org.apache.httpcomponents:httpclient:4.1
org.apache.httpcomponents:httpcore:4.1
org.eclipse.jetty:jetty-continuation:8.1.17.v20150415
org.eclipse.jetty:jetty-http:8.1.17.v20150415
org.eclipse.jetty:jetty-io:8.1.17.v20150415
org.eclipse.jetty:jetty-jndi:8.1.17.v20150415
org.eclipse.jetty:jetty-plus:8.1.17.v20150415
org.eclipse.jetty:jetty-security:8.1.17.v20150415
org.eclipse.jetty:jetty-server:8.1.17.v20150415
org.eclipse.jetty:jetty-servlet:8.1.17.v20150415
org.eclipse.jetty:jetty-util:8.1.17.v20150415
org.eclipse.jetty:jetty-webapp:8.1.17.v20150415
org.eclipse.jetty:jetty-xml:8.1.17.v20150415
org.eclipse.jetty.aggregate:jetty-servlet:8.1.17.v20150415
org.eclipse.jetty.orbit:javax.activation:1.1.0.v201105071233
org.eclipse.jetty.orbit:javax.mail.glassfish:1.4.1.v201005082020
org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016
org.eclipse.jetty.orbit:javax.transaction:1.1.1.v201105210645
org.javassist:javassist:3.18.2-GA
org.reflections:reflections:0.9.9
org.scala-lang:scala-compiler:2.10.5
org.scala-lang:scala-reflect:2.10.5
org.scalaz:scalaz-core_2.10:7.0.6
org.slf4j:slf4j-api:1.7.10
```

## Old *aloha-cli* Maven Dependencies

```
ai.h2o:google-analytics-java:1.1.2-H2O-CUSTOM:runtime
ai.h2o:h2o-core:3.8.2.3:compile
ai.h2o:h2o-genmodel:3.8.2.3:compile
com.eharmony:aloha-proto:2.0.1:compile
com.fasterxml:classmate:1.0.0:compile
com.github.deaktator:scala-runtime-manifest_2.10:0.0.1:compile
com.github.johnlangford:vw-jni:8.1.0:compile
com.github.multiworldtesting:explore-java:1.0.0:compile
com.github.rwl:jtransforms:2.4.0:runtime
com.github.scopt:scopt_2.10:3.3.0:compile
com.github.tony19:named-regexp:0.2.3:runtime
com.google.code.findbugs:annotations:2.0.1:compile
com.google.code.gson:gson:2.3.1:runtime
com.google.guava:guava:15.0:compile
com.google.protobuf:protobuf-java:2.4.1:compile
com.twitter:util-core_2.10:6.27.0:compile
com.twitter:util-function_2.10:6.27.0:compile
commons-codec:commons-codec:1.10:compile
commons-collections:commons-collections:3.0:runtime
commons-httpclient:commons-httpclient:3.1:runtime
commons-io:commons-io:2.4:compile
commons-lang:commons-lang:2.6:runtime
commons-logging:commons-logging:1.1.1:compile
commons-vfs:commons-vfs:1.0:compile
gov.nist.math:jama:1.0.3:runtime
io.spray:spray-json_2.10:1.3.1:compile
joda-time:joda-time:2.3:runtime
log4j:log4j:1.2.17:compile
net.java.dev.jets3t:jets3t:0.6.1:runtime
org.apache.commons:commons-math3:3.3:runtime
org.apache.commons:commons-vfs2:2.0:compile
org.apache.directory.studio:org.apache.commons.lang:2.6:runtime
org.apache.httpcomponents:httpclient:4.1:runtime
org.apache.httpcomponents:httpcore:4.1:runtime
org.eclipse.jetty:jetty-continuation:8.1.17.v20150415:runtime
org.eclipse.jetty:jetty-http:8.1.17.v20150415:runtime
org.eclipse.jetty:jetty-io:8.1.17.v20150415:runtime
org.eclipse.jetty:jetty-jndi:8.1.17.v20150415:runtime
org.eclipse.jetty:jetty-plus:8.1.17.v20150415:runtime
org.eclipse.jetty:jetty-security:8.1.17.v20150415:runtime
org.eclipse.jetty:jetty-server:8.1.17.v20150415:runtime
org.eclipse.jetty:jetty-servlet:8.1.17.v20150415:runtime
org.eclipse.jetty:jetty-util:8.1.17.v20150415:runtime
org.eclipse.jetty:jetty-webapp:8.1.17.v20150415:runtime
org.eclipse.jetty:jetty-xml:8.1.17.v20150415:runtime
org.eclipse.jetty.aggregate:jetty-servlet:8.1.17.v20150415:runtime
org.eclipse.jetty.orbit:javax.activation:1.1.0.v201105071233:runtime
org.eclipse.jetty.orbit:javax.mail.glassfish:1.4.1.v201005082020:runtime
org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016:runtime
org.eclipse.jetty.orbit:javax.transaction:1.1.1.v201105210645:runtime
org.javassist:javassist:3.18.2-GA:compile
org.reflections:reflections:0.9.9:compile
org.scala-lang:scala-compiler:2.10.5:compile
org.scala-lang:scala-library:2.10.5:compile
org.scala-lang:scala-reflect:2.10.5:compile
org.scalaz:scalaz-core_2.10:7.0.0:compile
org.slf4j:slf4j-api:1.7.10:compile
org.slf4j:slf4j-log4j12:1.7.10:compile
```

## New *aloha-cli* SBT Dependencies

```
ai.h2o:google-analytics-java:1.1.2-H2O-CUSTOM
ai.h2o:h2o-core:3.8.2.3
ai.h2o:h2o-genmodel:3.8.2.3
com.eharmony:aloha-proto:2.0.1
com.fasterxml:classmate:1.0.0
com.github.deaktator:scala-runtime-manifest_2.10:1.0.0
com.github.johnlangford:vw-jni:8.1.0
com.github.multiworldtesting:explore-java:1.0.0
com.github.rwl:jtransforms:2.4.0
com.github.scopt:scopt_2.10:3.3.0
com.github.tony19:named-regexp:0.2.3
com.google.code.findbugs:annotations:2.0.1
com.google.code.gson:gson:2.3.1
com.google.guava:guava:16.0.1
com.google.protobuf:protobuf-java:2.4.1
com.twitter:util-core_2.10:6.27.0
com.twitter:util-function_2.10:6.27.0
commons-codec:commons-codec:1.10
commons-collections:commons-collections:3.0
commons-httpclient:commons-httpclient:3.1
commons-io:commons-io:2.4
commons-lang:commons-lang:2.6
commons-logging:commons-logging:1.1.1
commons-vfs:commons-vfs:1.0
gov.nist.math:jama:1.0.3
io.spray:spray-json_2.10:1.3.1
joda-time:joda-time:2.3
log4j:log4j:1.2.17
net.java.dev.jets3t:jets3t:0.6.1
org.apache.commons:commons-math3:3.3
org.apache.commons:commons-vfs2:2.0
org.apache.directory.studio:org.apache.commons.lang:2.6
org.apache.httpcomponents:httpclient:4.1
org.apache.httpcomponents:httpcore:4.1
org.eclipse.jetty:jetty-continuation:8.1.17.v20150415
org.eclipse.jetty:jetty-http:8.1.17.v20150415
org.eclipse.jetty:jetty-io:8.1.17.v20150415
org.eclipse.jetty:jetty-jndi:8.1.17.v20150415
org.eclipse.jetty:jetty-plus:8.1.17.v20150415
org.eclipse.jetty:jetty-security:8.1.17.v20150415
org.eclipse.jetty:jetty-server:8.1.17.v20150415
org.eclipse.jetty:jetty-servlet:8.1.17.v20150415
org.eclipse.jetty:jetty-util:8.1.17.v20150415
org.eclipse.jetty:jetty-webapp:8.1.17.v20150415
org.eclipse.jetty:jetty-xml:8.1.17.v20150415
org.eclipse.jetty.aggregate:jetty-servlet:8.1.17.v20150415
org.eclipse.jetty.orbit:javax.activation:1.1.0.v201105071233
org.eclipse.jetty.orbit:javax.mail.glassfish:1.4.1.v201005082020
org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016
org.eclipse.jetty.orbit:javax.transaction:1.1.1.v201105210645
org.javassist:javassist:3.18.2-GA
org.reflections:reflections:0.9.9
org.scala-lang:scala-compiler:2.10.5
org.scala-lang:scala-reflect:2.10.5
org.scalaz:scalaz-core_2.10:7.0.6
org.slf4j:slf4j-api:1.7.10
org.slf4j:slf4j-log4j12:1.7.10
```

## Commands

To produce these lists, I used commands like the following and these removed `aloha-*` dependencies, test dependencies, then sorted.  Then I did a diff to determine the results.

- `sbt ++2.10.5 cli/dependencyList`
- `cd aloha-cli && mvn dependency:list`

**Comment by deaktator** [comment]
*Need to change the Guava version in* `aloha-cli` *to* **15.0**.

**Comment by deaktator** [comment]
## Set override dependencies

```scala
dependencyOverrides ++= Set(
  "org.scala-lang.modules" %% "scala-parser-combinators" % "1.0.4",
  "org.scala-lang.modules" %% "scala-xml" % "1.0.4",
  "com.google.guava" % "guava"  % "16.0.1",
  "commons-logging" % "commons-logging" % "1.1.1",
  "log4j" % "log4j" % "1.2.17"
)
```

This causes the dependencies to change in the projects as follows:

## CORE 
`scala-runtime-manifest_2.10:0.0.1` -> `scala-runtime-manifest_2.10:1.0.0`
`guava:15.0` -> `guava:16.0.1`
`commons-codec:1.10` -> `commons-codec:1.4`
`scalaz-core_2.10:7.0.0` -> `scalaz-core_2.10:7.0.6`

## VW
`scala-runtime-manifest_2.10:0.0.1` -> `scala-runtime-manifest_2.10:1.0.0`
`guava:15.0` -> `guava:16.0.1`
`commons-codec:1.10` -> `commons-codec:1.4`
`scalaz-core_2.10:7.0.0` -> `scalaz-core_2.10:7.0.6`

## H2O
`scala-runtime-manifest_2.10:0.0.1` -> `scala-runtime-manifest_2.10:1.0.0`
`commons-codec:1.10` -> `commons-codec:1.4`
`scalaz-core_2.10:7.0.0` -> `scalaz-core_2.10:7.0.6`

## CLI
`scala-runtime-manifest_2.10:0.0.1` -> `scala-runtime-manifest_2.10:1.0.0`
`guava:15.0` -> `guava:16.0.1`
`commons-codec:1.10` -> `commons-codec:1.4`
`scalaz-core_2.10:7.0.0` -> `scalaz-core_2.10:7.0.6`

**Review by jon-morra-zefr — APPROVED** [review]
I think this looks great.  My only question is why bother to leave the pom files in there at all?

**Comment by deaktator** [comment]
Good. Call.  Will remove now.

**Pull request merged**
