### PR TITLE
Adding PR template

### LINKED ISSUE #183: Add PR template

### PR DESCRIPTION
**Pull request by amirziai**
### Summary
Adding PR template

### Bug Fixes/New Features
N/A

### How to Verify
N/A

### Side Effects
N/A

### Resolves
#183 

### Tests
N/A

### Code Reviewer(s)
@deaktator

### CODE REVIEW

**Comment by deaktator** [comment]
I would make it like the following.  That way it's less than 80 chars wide, reordered, and has a more githubby issues feel.

```
## Summary
The summary should expand on the title of the pull request. What is the 
expected effect of the pull request? Specifically, indicate how the behavior 
will be different than before the pull request.

## Resolves
* Fixes issue #1
* Fixes issue #2

## Bug Fixes/New Features
* Bullet list overview of bug fixes or new features added.
* Some other feature bullet.

## Side Effects
Does the pull request contain any side effects? This should list non-obvious 
things that have changed in the request.

## How to Verify
How can reviewers verify the request has the intended effect? This should 
include descriptions of any new tests that are added or old tests that are 
updated. It should also indicate how the code was tested.

## Tests
What tests were created or changed for this feature or fix? Do all tests 
pass, and if not, why?

### Code Reviewer(s)
@<code reviewer>, @<additional code reviewer>
```

**Review by deaktator — APPROVED** [review]
Looks good.

**Comment by deaktator** [comment]
Thanks @amirziai!

**Comment by deaktator** [comment]
@amirziai If you title the PR "Closes [*pound sign*][*issue number*]", it will automatically close the associated issue.  Just wanted to let you know.

**Comment by amirziai** [comment]
@deaktator didn't know, thanks!

**Pull request merged**
